version: '3'

services:
  mariadb:
    container_name: mariadb
    restart: always
    build: 
      context: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    .env_file:
      - .env
    networks:
      - intra
    image: mariadb
    init: true
    pull_policy: never

  nginx:
    image: debian:buster
    restart: always
    ports:
      - "443:443"
    volumes:
      - data:/var/www/html
    networks:
      - intra
    tty: true

  wordpress:
    image: debian:buster
    restart: always
    volumes:
      - data:/var/www/html
    expose:
      - "9000"
    networks:
      - intra
    tty: true

volumes:
  data: {}
    
networks:
  intra:
    driver: bridge